name: dartpad_gen_cli
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/piedcipher/dotslash3.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path:
  http:
  meta:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
